// <auto-generated />
using System;
using BudgetTracker.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _04__Infrastructure.Migrations
{
    [DbContext(typeof(BudgetTrackerDbContext))]
    [Migration("20250627130723_ApplicationModularServices")]
    partial class ApplicationModularServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BudgetTracker.Domain.Entities.BudgetContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BudgetContainers");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.BudgetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetContainerId");

                    b.ToTable("BudgetItems");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Rent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.CategoryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryMappings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CategoryName = "Food",
                            GroupName = "Necessities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CategoryName = "Rent",
                            GroupName = "Necessities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CategoryName = "Entertainment",
                            GroupName = "Discretionary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CategoryName = "Investments",
                            GroupName = "Savings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CategoryName = "Utilities",
                            GroupName = "Necessities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CategoryName = "Transportation",
                            GroupName = "Necessities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CategoryName = "Healthcare",
                            GroupName = "Necessities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CategoryName = "Clothing",
                            GroupName = "Discretionary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CategoryName = "Education",
                            GroupName = "Discretionary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CategoryName = "Miscellaneous",
                            GroupName = "Discretionary"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SavingGoalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SavingGoalsId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetContainerId");

                    b.HasIndex("SavingGoalId");

                    b.HasIndex("SavingGoalsId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetContainerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetContainerId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.PlannedExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Period")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SavingGoalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetContainerId");

                    b.HasIndex("SavingGoalId");

                    b.ToTable("PlannedExpenses");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.PlannedIncome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetContainerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetContainerId");

                    b.ToTable("PlannedIncomes", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.SavingGoals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetContainerId");

                    b.ToTable("SavingGoals");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.BudgetItem", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.BudgetContainer", "BudgetContainer")
                        .WithMany("BudgetItems")
                        .HasForeignKey("BudgetContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "ActualAmount", b1 =>
                        {
                            b1.Property<Guid>("BudgetItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ActualAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("ActualAmount_Currency");

                            b1.HasKey("BudgetItemId");

                            b1.ToTable("BudgetItems");

                            b1.WithOwner()
                                .HasForeignKey("BudgetItemId");
                        });

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "PlannedAmount", b1 =>
                        {
                            b1.Property<Guid>("BudgetItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PlannedAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("PlannedAmount_Currency");

                            b1.HasKey("BudgetItemId");

                            b1.ToTable("BudgetItems");

                            b1.WithOwner()
                                .HasForeignKey("BudgetItemId");
                        });

                    b.Navigation("ActualAmount")
                        .IsRequired();

                    b.Navigation("BudgetContainer");

                    b.Navigation("PlannedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Expense", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.BudgetContainer", "BudgetContainer")
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Domain.Entities.SavingGoals", "SavingGoal")
                        .WithMany()
                        .HasForeignKey("SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BudgetTracker.Domain.Entities.SavingGoals", null)
                        .WithMany("Expenses")
                        .HasForeignKey("SavingGoalsId");

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("Amount_Currency");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("BudgetContainer");

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Income", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.BudgetContainer", "BudgetContainer")
                        .WithMany("Incomes")
                        .HasForeignKey("BudgetContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "ActualAmount", b1 =>
                        {
                            b1.Property<Guid>("IncomeId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ActualAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("ActualAmount_Currency");

                            b1.HasKey("IncomeId");

                            b1.ToTable("Incomes");

                            b1.WithOwner()
                                .HasForeignKey("IncomeId");
                        });

                    b.Navigation("ActualAmount")
                        .IsRequired();

                    b.Navigation("BudgetContainer");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.PlannedExpense", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.BudgetContainer", "BudgetContainer")
                        .WithMany()
                        .HasForeignKey("BudgetContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Domain.Entities.SavingGoals", "SavingGoal")
                        .WithMany()
                        .HasForeignKey("SavingGoalId");

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PlannedExpenseId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("Amount_Currency");

                            b1.HasKey("PlannedExpenseId");

                            b1.ToTable("PlannedExpenses");

                            b1.WithOwner()
                                .HasForeignKey("PlannedExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("BudgetContainer");

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.PlannedIncome", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.BudgetContainer", "BudgetContainer")
                        .WithMany("PlannedIncomes")
                        .HasForeignKey("BudgetContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PlannedIncomeId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("Amount_Currency");

                            b1.HasKey("PlannedIncomeId");

                            b1.ToTable("PlannedIncomes");

                            b1.WithOwner()
                                .HasForeignKey("PlannedIncomeId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("BudgetContainer");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.SavingGoals", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.BudgetContainer", "BudgetContainer")
                        .WithMany("SavingGoals")
                        .HasForeignKey("BudgetContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "CurrentAmount", b1 =>
                        {
                            b1.Property<Guid>("SavingGoalsId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("CurrentAmount_Currency");

                            b1.HasKey("SavingGoalsId");

                            b1.ToTable("SavingGoals");

                            b1.WithOwner()
                                .HasForeignKey("SavingGoalsId");
                        });

                    b.OwnsOne("BudgetTracker.Domain.ValueObjects.Money", "TargetAmount", b1 =>
                        {
                            b1.Property<Guid>("SavingGoalsId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TargetAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("USD")
                                .HasColumnName("TargetAmount_Currency");

                            b1.HasKey("SavingGoalsId");

                            b1.ToTable("SavingGoals");

                            b1.WithOwner()
                                .HasForeignKey("SavingGoalsId");
                        });

                    b.Navigation("BudgetContainer");

                    b.Navigation("CurrentAmount")
                        .IsRequired();

                    b.Navigation("TargetAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.BudgetContainer", b =>
                {
                    b.Navigation("BudgetItems");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("PlannedIncomes");

                    b.Navigation("SavingGoals");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.SavingGoals", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
